/* eslint-disable */
exports.AngularTypeEnum = { extends: [ '@commitlint/config-angular-type-enum' ],
  rules: 
   { 'type-enum': 
      [ 2,
        'always',
        [ 'build',
          'ci',
          'docs',
          'feat',
          'fix',
          'perf',
          'refactor',
          'revert',
          'style',
          'test' ] ] } };
exports.Angular = { extends: [ '@commitlint/config-angular' ],
  rules: 
   { 'body-leading-blank': [ 1, 'always' ],
     'footer-leading-blank': [ 1, 'always' ],
     'header-max-length': [ 2, 'always', 72 ],
     'scope-case': [ 2, 'always', 'lower-case' ],
     'subject-case': 
      [ 2,
        'never',
        [ 'sentence-case', 'start-case', 'pascal-case', 'upper-case' ] ],
     'subject-empty': [ 2, 'never' ],
     'subject-full-stop': [ 2, 'never', '.' ],
     'type-case': [ 2, 'always', 'lower-case' ],
     'type-empty': [ 2, 'never' ],
     'type-enum': 
      [ 2,
        'always',
        [ 'build',
          'ci',
          'docs',
          'feat',
          'fix',
          'perf',
          'refactor',
          'revert',
          'style',
          'test' ] ] } };
exports.Conventional = { extends: [ '@commitlint/config-conventional' ],
  rules: 
   { 'body-leading-blank': [ 1, 'always' ],
     'footer-leading-blank': [ 1, 'always' ],
     'header-max-length': [ 2, 'always', 72 ],
     'scope-case': [ 2, 'always', 'lower-case' ],
     'subject-case': 
      [ 2,
        'never',
        [ 'sentence-case', 'start-case', 'pascal-case', 'upper-case' ] ],
     'subject-empty': [ 2, 'never' ],
     'subject-full-stop': [ 2, 'never', '.' ],
     'type-case': [ 2, 'always', 'lower-case' ],
     'type-empty': [ 2, 'never' ],
     'type-enum': 
      [ 2,
        'always',
        [ 'build',
          'chore',
          'ci',
          'docs',
          'feat',
          'fix',
          'perf',
          'refactor',
          'revert',
          'style',
          'test' ] ] } };
exports.LernaScopes = { extends: [ '@commitlint/config-lerna-scopes' ],
  rules: { 'scope-enum': [ 2, 'always', [] ] } };
exports.Patternplate = { extends: [ '@commitlint/config-patternplate' ],
  rules: 
   { 'body-leading-blank': [ 1, 'always' ],
     'footer-leading-blank': [ 1, 'always' ],
     'header-max-length': [ 2, 'always', 72 ],
     'scope-case': [ 2, 'always', 'lower-case' ],
     'subject-case': 
      [ 2,
        'never',
        [ 'sentence-case', 'start-case', 'pascal-case', 'upper-case' ] ],
     'subject-empty': [ 2, 'never' ],
     'subject-full-stop': [ 2, 'never', '.' ],
     'type-case': [ 2, 'always', 'lower-case' ],
     'type-empty': [ 2, 'never' ],
     'type-enum': 
      [ 2,
        'always',
        [ 'build',
          'ci',
          'docs',
          'feat',
          'fix',
          'perf',
          'refactor',
          'revert',
          'style',
          'test' ] ],
     'scope-enum': [ 2, 'always', [ 'system' ] ] } };
